function changeColor()
{
   alert(" Now you will regret cliking me!!");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");
   alert(" :P");

   var titleSpan = document.getElementById("pageTitle");
   titleSpan.style.backgroundColor = "purple";
}